---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present virtualenv={{ venv_home }}

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=imagersite.conf.j2 dest=/etc/init/imagersite.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=imagersite state=restarted
