---

- name: Create RDS instance
  local_action:
    module: rds
    command: create
    db_engine: postgres
    db_name: imagerdb
    instance_name: imager
    instance_type: db.t2.micro
    license_model: postgresql-license
    vpc_security_groups: sg-4b1bbf32
    zone: us-west-2a
    region: us-west-2
    size: 5
    username: imageruser
    password: "{{ DBPASS }}"
